### ISSUE TITLE
ERROR: Your storage adapter does not inherit from the Storage Base. 

### ISSUE THREAD

**Issue by andrienpecson** [robincsamuel/ghost-google-drive#6]
I am experiencing the adapter error: Here is my config block for the storage.

`storage: {
            active: 'ghost-google-drive',
            'ghost-google-drive': {
                key: {
                    private_key_id: "XXXXXXXXXXXXXXXXXXX",
                    private_key: "XXXXXXXXXXXXXXXXXXXXXX",
                    client_email: "XXXXXXXXXXXXXXXXXXXXXX",
                    client_id: "XXXXXXXXXXXXXXXXXXXXXXXX",
                }
            }
        }`

And here is the error log:

ERROR: Your storage adapter does not inherit from the Storage Base.                                                         

 Error  
    at Error.IncorrectUsage (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/core/server/errors/incorrect-usage.js:3:18)  
    at Object.getStorage (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/core/server/storage/index.js:54:15)  
    at setupMiddleware (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/core/server/middleware/index.js:126:44)  
    at /opt/lampp/htdocs/gitprojects/ghost-geisermaclang/core/server/index.js:188:9  
    at tryCatcher (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/util.js:16:23)  
    at Promise._settlePromiseFromHandler (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release
/promise.js:510:31)  
    at Promise._settlePromise (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.js
:567:18)  
    at Promise._settlePromise0 (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.j
s:612:10)  
    at Promise._settlePromises (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.j
s:691:18)  
    at Promise._fulfill (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.js:636:1
8)  
    at PromiseArray._resolve (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise_arr
ay.js:125:19)  
    at PromiseArray._promiseFulfilled (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/pr
omise_array.js:143:14)  
    at Promise._settlePromise (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.js
:572:26)  
    at Promise._settlePromise0 (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.j
s:612:10)  
    at Promise._settlePromises (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/promise.j
s:691:18)  
    at Async._drainQueue (/opt/lampp/htdocs/gitprojects/ghost-geisermaclang/node_modules/bluebird/js/release/async.js:138:16
)

**Comment by lalahehe** [comment]
try this, it works for me with v0.11.3

```
'use strict'
/*
 * Google drive storage for ghost blog
 * @author : Robin C Samuel <hi@robinz.in> http://robinz.in
 * @date : 11th August 2015
 */
var Promise = require('bluebird'),
  fs = require('fs'),
  googleapis = require('googleapis'),
  https = require('https'),
  BaseStore = require('../../../core/server/storage/base'),
  util = require('util');

function ghostGoogleDrive(config) {
  BaseStore.call(this);
  this.config = config || {};
};

util.inherits(ghostGoogleDrive, BaseStore);

ghostGoogleDrive.prototype.save = function(file) {
  var _this = this;
  return new Promise(function(resolve, reject) {
    var key = _this.config.key
    var jwtClient = new googleapis.auth.JWT(key.client_email, null, key.private_key, ['https://www.googleapis.com/auth/drive'], null);

    jwtClient.authorize(function(err, tokens) {
      if (err) {
        console.log(err);
        reject(err)
        return;
      }

      var drive = googleapis.drive({
        version: 'v2',
        auth: jwtClient
      });
      drive.files.insert({
        resource: {
          title: file.name,
          mimeType: file.type
        },
        media: {
          mimeType: file.type,
          body: fs.createReadStream(file.path)
        }
      }, function(err, data) {
        if (err) {
          console.log(err)
          reject(err)
          return;
        }
        // make the url looks like a file
        resolve('/content/images/' + data.id + '.' + data.fileExtension);
      });
    });
  });
};

ghostGoogleDrive.prototype.serve = function() {
  var _this = this;
  return function(req, res, next) {
    // get the file id from url
    var id = req.path.replace('/', '').split('.')[0];

    var key = _this.config.key
    var jwtClient = new googleapis.auth.JWT(key.client_email, null, key.private_key, ['https://www.googleapis.com/auth/drive'], null);
    //auth
    jwtClient.authorize(function(err, tokens) {
      if (err) {
        console.log(err);
        next()
      }
      var drive = googleapis.drive({
        version: 'v2',
        auth: jwtClient
      });
      drive.files.get({
        fileId: id
      }, function(err, file) {
        if (!err) {
          var newReq = https.request(file.downloadUrl + '&access_token=' + tokens.access_token, function(newRes) {
            // Modify google headers here to cache!
            var headers = newRes.headers;
            headers['content-disposition'] = "attachment; filename=" + file.originalFilename;
            headers['cache-control'] = 'public, max-age=1209600';
            delete headers['expires'];
            res.writeHead(newRes.statusCode, headers);
            // pipe the file
            newRes.pipe(res);
          }).on('error', function(err) {
            res.statusCode = 500;
            res.end();
          });
          req.pipe(newReq);
        } else {
          next()
        }

      });
    });
  };
};

ghostGoogleDrive.prototype.exists = function (filename) {
    return false;
};

ghostGoogleDrive.prototype.delete = function (fileName, targetDir) {
    return true;
};

module.exports = ghostGoogleDrive

```

**Comment by robincsamuel** [comment]
@lalahehe Included your changes.
